# PostgreSQL. Versions 8.2 and up are supported.

<% user = ENV["POSTGRES_USER"] %>
<% password = ENV["POSTGRES_PASSWORD"] %>
<% db_service = ENV.fetch("DATABASE_SERVICE_NAME","").upcase %>

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: <%= user %>
  password: <%= password %>
  host: <%= ENV["#{db_service}_SERVICE_HOST"] || "postgres" %>
  port: <%= ENV["#{db_service}_SERVICE_PORT"] || 5432 %>
  database: <%= ENV["POSTGRES_DB"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
