---
- name: "Create Dockerfile for foreman"
  template:
    src: "Dockerfile.j2"
    dest: "{{ build_dir }}/{{ image }}/Dockerfile"
    mode: 0600

- name: "Copy container assets for foreman to build dir"
  copy:
    src: "{{ role_path }}/files/container-assets"
    dest: "{{ build_dir }}/{{ image }}"
    mode: preserve
