---
- hosts: localhost
  gather_facts: no
  vars:
    image: foreman
  vars_files:
    - vars/build-image-vars.yml
  roles:
    - role: create-workspace
    - role: foreman-dockerfile
    - role: build-image
    - role: push-image
