---
- hosts: localhost
  gather_facts: no
  vars:
    version: 2.0
    version_build: 1
    cleanup: false
    rpms_to_install: []
  roles:
    - role: create_dockerfile
      vars:
        image: foreman
        version_build: "{{ foreman_version_build }}"
