---
- hosts: localhost
  gather_facts: no
  vars:
    image: foreman-proxy
    configs_to_copy: []
  vars_files:
    - vars/build-image-vars.yml
  roles:
    - role: create-workspace
    - role: foreman-proxy-dockerfile
    - role: build-image
    - role: push-image
