---
name: Test ansible run

on: [workflow_dispatch]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run playbook
        run: ansible-playbook ./playbooks/test.yml